### ISSUE TITLE
Ollama provider 404s — createOpenAI uses Responses API which Ollama doesn't support

### ISSUE THREAD

**Issue by wihodges** [abubakarsiddik31/axiom-wiki#1]
# Ollama provider 404s on `/api/responses` — uses Responses API by default

## Summary

With `provider: ollama` configured, every LLM call 404s against any Ollama version (tested on 0.20.2). Ingest fails immediately.

## Reproduction

```bash
npm install -g axiom-wiki@0.1.0
mkdir /tmp/axiom-test && cd /tmp/axiom-test
cat > .axiom/config.json <<'EOF'
{
  "provider": "ollama",
  "model": "qwen3:8b",
  "wikiDir": "/tmp/axiom-test/wiki",
  "rawDir": "/tmp/axiom-test/raw",
  "ollamaBaseUrl": "http://localhost:11434/api"
}
EOF
echo "# test" > raw/test.md
axiom-wiki ingest
```

Result:
```
Upstream LLM API error {
  url: 'http://localhost:11434/api/responses',
  provider: 'openai.responses',
  statusCode: 404,
  responseBody: '404 page not found'
}
```

## Root cause

In `dist/src/agent/index.js:33-36`:

```js
case 'ollama': {
    const baseURL = config.ollamaBaseUrl ?? 'http://localhost:11434/api';
    return createOpenAI({ baseURL, apiKey: 'ollama' })(modelId);
}
```

Two problems:

1. `createOpenAI(...)(modelId)` is the **Responses API** shape in recent `@ai-sdk/openai` releases, which appends `/responses` to the base URL. Ollama does not implement the Responses API.
2. Default `baseURL` is `/api`, but Ollama's OpenAI-compatible endpoint is `/v1` (its native API at `/api` has different routes).

## Fix

```js
case 'ollama': {
    const baseURL = config.ollamaBaseUrl ?? 'http://localhost:11434/v1';
    return createOpenAI({ baseURL, apiKey: 'ollama' }).chat(modelId);
}
```

Confirmed working with qwen3:8b on Ollama 0.20.2.

Happy to open a PR if helpful.

**Comment by abubakarsiddik31** [comment]
@wihodges the issue is fixed. Please install the latest version.

More about the fix: https://github.com/abubakarsiddik31/axiom-wiki/releases/tag/v0.3.1

Thank you for creating the first issue!
